### ISSUE TITLE
first Run throw a  exception 

### ISSUE THREAD

**Issue by vipheyue** [Nightonke/CoCoin#11]
FATAL EXCEPTION: main
                                                                      Process: com.nightonke.cocoin, PID: 18852
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nightonke.cocoin/com.nightonke.saver.activity.MainActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class android.support.v7.widget.Toolbar
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2200)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250)
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:136)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5105)
                                                                          at java.lang.reflect.Method.invokeNative(Native Method)
                                                                          at java.lang.reflect.Method.invoke(Method.java:515)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
                                                                          at dalvik.system.NativeStart.main(Native Method)
                                                                       Caused by: android.view.InflateException: Binary XML file line #19: Error inflating class android.support.v7.widget.Toolbar
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:620)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267)
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129)
                                                                          at com.nightonke.saver.activity.MainActivity.onCreate(MainActivity.java:149)
                                                                          at android.app.Activity.performCreate(Activity.java:5275)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5105) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: java.lang.reflect.InvocationTargetException
                                                                          at java.lang.reflect.Constructor.constructNative(Native Method)
                                                                          at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
                                                                          at android.view.LayoutInflater.createView(LayoutInflater.java:594)
                                                                          at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                                                                          at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                                                                          at android.view.LayoutInflater.inflate(LayoutInflater.java:353) 
                                                                          at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:267) 
                                                                          at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:129) 
                                                                          at com.nightonke.saver.activity.MainActivity.onCreate(MainActivity.java:149) 
                                                                          at android.app.Activity.performCreate(Activity.java:5275) 
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2164) 
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2250) 
                                                                          at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1200) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:136) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5105) 
                                                                          at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                          at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
                                                                          at dalvik.system.NativeStart.main(Native Method) 
                                                                       Caused by: android.content.res.Resources$NotFoundException: File res/drawable-v19/abc_ic_ab_back_material.xml from drawable resource ID #0x7f020019

**Comment by Nightonke** [comment]
This error is caused by the lost of the drawable in the file v-19. You can get solutions [here](https://github.com/Nightonke/LeeCo/issues/1).
