### ISSUE TITLE
 Error inflating class android.support.v7.widget.Toolbar

### ISSUE THREAD

**Issue by wincansoft** [Nightonke/CoCoin#15]
运行时出现启动画面后闪退，下面是报错信息：
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nightonke.cocoin/com.nightonke.saver.activity.MainActivity}: android.view.InflateException: Binary XML file line #19: Error inflating class android.support.v7.widget.Toolbar
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
......
 at com.nightonke.saver.activity.MainActivity.onCreate(MainActivity.java:145)

**Comment by Nightonke** [comment]
Did this bug happen when you trying to build CoCoin in your android studio? Thanks for your reporting.
